// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/recipe": {
            "get": {
                "description": "Возвращает случайный рецепт из выбранной категории (breakfast, lunch, dinner, snack)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "Получить случайный рецепт",
                "parameters": [
                    {
                        "enum": [
                            "breakfast",
                            "lunch",
                            "dinner",
                            "snack"
                        ],
                        "type": "string",
                        "description": "Категория блюда",
                        "name": "category",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Recipe"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Ingredient": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Количество: \"200мл\"",
                    "type": "string"
                },
                "name": {
                    "description": "Название: \"Молоко\"",
                    "type": "string"
                }
            }
        },
        "model.Recipe": {
            "type": "object",
            "properties": {
                "carbs": {
                    "type": "integer"
                },
                "category": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "fat": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "ingredients": {
                    "description": "Слайс (массив) ингредиентов",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Ingredient"
                    }
                },
                "instructions": {
                    "type": "string"
                },
                "kcal": {
                    "type": "integer"
                },
                "protein": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "GoodFood API",
	Description:      "API для получения случайных рецептов блюд\n\nКатегории: breakfast, lunch, dinner, snack",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
